# image: https://hub.docker.com/r/dbeaver/cloudbeaver
# config docs: https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration

version: "3.8"

services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      restart: always
      ports:
       - '8978:8978'
      volumes: 
       - cloudbeaver:/opt/cloudbeaver/workspace            

networks:
  default:
    name: test
    external: true

volumes:
  cloudbeaver:
