services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
