services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin4:
    depends_on:
      - postgres
    container_name: pgadmin4
    image: dpage/pgadmin4:8.6
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=Pa55w0rd

volumes:
  postgres:
